M48
; DRILL file {KiCad 9.0.5} date 2025-12-30T15:27:52+0900
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-12-30T15:27:52+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.5
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.700
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.750
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C0.800
%
G90
G05
T1
X164.5Y-78.0
X164.5Y-83.08
T2
X144.0Y-80.0
X146.0Y-80.0
T3
X152.5Y-79.5
X152.5Y-82.0
X159.5Y-79.5
X159.5Y-82.0
M30
