M48
; DRILL file {KiCad 9.0.5} date 2026-01-13T09:43:51+0900
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-01-13T09:43:51+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.5
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.700
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.800
%
G90
G05
T1
X164.0Y-77.46
X164.0Y-82.54
T2
X152.25Y-79.0
X152.25Y-81.5
X157.5Y-79.0
X157.5Y-81.5
M30
